version: '3'
services:
  rabbitmq:
    build: rabbitmq/.
    container_name: ${RABBITMQ_HOST}
    ports:
        - 15672:15672
        - 5672:5672
    healthcheck:
        test: ["CMD", "curl", "-f", "localhost:15672"]
        interval: 5s
        timeout: 15s
        retries: 5
  adminer:
    image: adminer:latest
    ports:
        - 8080:8080
    depends_on:
      - database_order
    restart: always
  database_order:
    image: mysql:latest
    container_name: ${DATABASE_ORDER_HOST}
    ports: # TODO not needed?
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ORDER_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DATABASE_ORDER_NAME}
      - MYSQL_USER=${DATABASE_ORDER_USER}
      - MYSQL_PASSWORD=${DATABASE_ORDER_PASSWORD}
    volumes:
      - mysql_data_order:/var/lib/mysql
    healthcheck:
        test: "mysql --user=root --password=${DATABASE_ORDER_PASSWORD_ROOT} --execute \"SHOW DATABASES;\""
        interval: 10s
        timeout: 15s
        retries: 5
  order:
    build:
      context: order/.
    ports:
      - 8000:8000
    depends_on:
      database_order:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment: # TODO use env file...
      - MYSQL_HOST=${DATABASE_ORDER_HOST}
      - MYSQL_DATABASE=${DATABASE_ORDER_NAME}
      - MYSQL_PORT=${DATABASE_ORDER_PORT}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DATABASE_ORDER_PASSWORD_ROOT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    volumes:
      - ./order/app:/app
  database_financial:
    image: mysql:latest
    container_name: ${DATABASE_FINANCIAL_HOST}
    ports: # TODO not needed?
      - 33060:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_FINANCIAL_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DATABASE_FINANCIAL_NAME}
      - MYSQL_USER=${DATABASE_FINANCIAL_USER}
      - MYSQL_PASSWORD=${DATABASE_FINANCIAL_PASSWORD}
    volumes:
      - mysql_data_financial:/var/lib/mysql
    healthcheck:
        test: "mysql --user=root --password=${DATABASE_FINANCIAL_PASSWORD_ROOT} --execute \"SHOW DATABASES;\""
        interval: 10s
        timeout: 15s
        retries: 5
  financial:
    build:
      context: financial/.
    ports:
      - 8001:8000
    depends_on:
      database_financial:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment: # TODO use env file...
      - MYSQL_HOST=${DATABASE_FINANCIAL_HOST}
      - MYSQL_DATABASE=${DATABASE_FINANCIAL_NAME}
      - MYSQL_PORT=${DATABASE_FINANCIAL_PORT}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DATABASE_FINANCIAL_PASSWORD_ROOT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    volumes:
      - ./financial/app:/app
  database_warehouse:
    image: mysql:latest
    container_name: ${DATABASE_WAREHOUSE_HOST}
    ports: # TODO not needed?
      - 3308:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_WAREHOUSE_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DATABASE_WAREHOUSE_NAME}
      - MYSQL_USER=${DATABASE_WAREHOUSE_USER}
      - MYSQL_PASSWORD=${DATABASE_WAREHOUSE_PASSWORD}
    volumes:
      - mysql_data_warehouse:/var/lib/mysql
    healthcheck:
        test: "mysql --user=root --password=${DATABASE_WAREHOUSE_PASSWORD_ROOT} --execute \"SHOW DATABASES;\""
        interval: 10s
        timeout: 15s
        retries: 5
  warehouse:
    build:
      context: warehouse/.
    ports:
      - 8002:8000
    depends_on:
      database_warehouse:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment: # TODO use env file...
      - MYSQL_HOST=${DATABASE_WAREHOUSE_HOST}
      - MYSQL_DATABASE=${DATABASE_WAREHOUSE_NAME}
      - MYSQL_PORT=${DATABASE_WAREHOUSE_PORT}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DATABASE_WAREHOUSE_PASSWORD_ROOT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    volumes:
      - ./warehouse/app:/app


volumes:
  mysql_data_order:
  mysql_data_financial:
  mysql_data_warehouse:
